
GET http://localhost:5000/users

###

GET http://localhost:5000/users/677fa6419e03ad8fce4ca6a4


###

POST http://localhost:5000/register
Content-type: application/json

{
    "username": "kawa2",
    "password": "tamere94",
    "email": "admin@email.com",
    "name": "admin"
}

###

POST http://localhost:5000/login
Content-type: application/json

{
    "username": "kawa2",
    "password": "tamere94"
}
