POST http://localhost:5000/auth/login1
Content-type: application/json

{
    "username": "admin",
    "password": "admin"
}


###

POST http://localhost:5000/api/authentication/login
Content-type: application/json

{
    "username": "admin",
    "password": "admin"
}
