
GET http://localhost:5000/auth/

###

POST http://localhost:5000/auth/register
Content-type: application/json

{
    "name": "admin1",
    "username": "admin1",
    "password": "admin1",
    "email": "admin1@admmin.com"
}

###

POST http://localhost:5000/auth/register1
Content-type: application/json

{
    "username": "admin2",
    "password": "admin2",
    "email": "admin2@admmin.com",
    "name": "admin2"
}

###

POST http://localhost:5000/auth/login
Content-type: application/json

{
    "username": "admin",
    "password": "admin"
}

###

POST http://localhost:5000/auth/logout1
Content-type: application/json

{
}
