
GET http://localhost:5000/auth/

###

POST http://localhost:5000/auth/register
Content-type: application/json

{
    "username": "admin",
    "password": "admin",
    "email": "admin@admmin.com",
    "name": "admin"
}

###

POST http://localhost:5000/auth/login
Content-type: application/json

{
    "username": "admin1",
    "password": "admin1"
}
