POST http://localhost:5000/auth/login1
Content-type: application/json

{
    "username": "admin",
    "password": "admin"
}

###
POST http://localhost:5000/api/authentication/login
Content-type: application/json

{
    "username": "admin",
    "password": "admin"
}


###

GET http://localhost:5000/cam/getUserCams
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQ4NzkzNjA1LCJleHAiOjE3NDg3OTU0MDV9.JMSOEAchh_DZwTer26oSFCHqaW6G91AjnxbqYJ-yKaM

{

}

###

GET http://localhost:5000/api/cameras/getUserCams
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQ4ODA2MDQzLCJleHAiOjE3NDg4MDY5NDN9.T9EecAu3kRdAggOgsd376fVhxMfUsIrSlAw_ECL5zbc

{

}


###
DELETE http://localhost:5000/cam/rm/CAM-H5
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQ4NzkzNjA1LCJleHAiOjE3NDg3OTU0MDV9.JMSOEAchh_DZwTer26oSFCHqaW6G91AjnxbqYJ-yKaM

{

}

###
POST http://localhost:5000/cam/newcam
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQ4ODAyMjgxLCJleHAiOjE3NDg4MDQwODF9.loY2b_h2_QOxKU3iUcsBm2BdRPsqwjNEwjWXlVPcIRw

{
    "cameraName": "CAM-5",
    "cameraType": "basic"
}