


POST http://localhost:5000/cam/AddNewCamera
Content-type: application/json

{
    "cameraName": "CAM-H1",
    "cameraType": "basic"
}

###

GET http://localhost:5000/cam/test

###

GET  http://localhost:5000/cam/getUserCams
